apiVersion: apps/v1
kind: Deployment
metadata:
  name: nlk-deployment
  namespace: nlk
  labels:
    app: nlk
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nlk
  template:
    metadata:
      labels:
        app: nlk
    spec:
      containers:
        - name: nginx-loadbalancer-kubernetes
          image: ciroque/nginx-loadbalancer-kubernetes:dev-11
#          image: ghcr.io/nginxinc/nginx-loadbalancer-kubernetes:125
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 51031
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /livez
              port: 51031
            initialDelaySeconds: 5
            periodSeconds: 2
          readinessProbe:
            httpGet:
              path: /readyz
              port: 51031
            initialDelaySeconds: 5
            periodSeconds: 2
      serviceAccountName: nginx-loadbalancer-kubernetes
